/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        'montserrat': ['var(--font-montserrat)', 'ui-sans-serif', 'system-ui'],
        'lora': ['var(--font-lora)', 'ui-serif', 'Georgia'],
      },
      colors: {
        primary: {
          50: 'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
        },
        accent: {
          50: 'var(--color-accent-50)',
          100: 'var(--color-accent-100)',
          200: 'var(--color-accent-200)',
          300: 'var(--color-accent-300)',
          400: 'var(--color-accent-400)',
          500: 'var(--color-accent-500)',
          600: 'var(--color-accent-600)',
          700: 'var(--color-accent-700)',
          800: 'var(--color-accent-800)',
          900: 'var(--color-accent-900)',
        },
        cta: {
          50: 'var(--color-cta-50)',
          100: 'var(--color-cta-100)',
          200: 'var(--color-cta-200)',
          300: 'var(--color-cta-300)',
          400: 'var(--color-cta-400)',
          500: 'var(--color-cta-500)',
          600: 'var(--color-cta-600)',
          700: 'var(--color-cta-700)',
          800: 'var(--color-cta-800)',
          900: 'var(--color-cta-900)',
        },
        'primary-warm': {
          DEFAULT: 'var(--color-primary-warm)',
          hover: 'var(--color-primary-warm-hover)',
        },
        trust: {
          50: 'var(--color-trust-50)',
          100: 'var(--color-trust-100)',
          200: 'var(--color-trust-200)',
          300: 'var(--color-trust-300)',
          400: 'var(--color-trust-400)',
          500: 'var(--color-trust-500)',
          600: 'var(--color-trust-600)',
          700: 'var(--color-trust-700)',
          800: 'var(--color-trust-800)',
          900: 'var(--color-trust-900)',
        },
      },
      spacing: {
        'xs': 'var(--spacing-xs)',
        'sm': 'var(--spacing-sm)',
        'md': 'var(--spacing-md)',
        'lg': 'var(--spacing-lg)',
        'xl': 'var(--spacing-xl)',
        '2xl': 'var(--spacing-2xl)',
      },
      fontSize: {
        'xs': 'var(--font-size-xs)',
        'sm': 'var(--font-size-sm)',
        'base': 'var(--font-size-base)',
        'lg': 'var(--font-size-lg)',
        'xl': 'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
        '3xl': 'var(--font-size-3xl)',
        '4xl': 'var(--font-size-4xl)',
        '5xl': 'var(--font-size-5xl)',
      },
    },
  },
  plugins: [],
}